defmodule Depdep.Key do
  @moduledoc """
  The recursive Merkle key.

  A dependency's compiled output is a function of its dependencies' compiled
  output, not just its own source. Elixir resolves a great deal at compile time
  and bakes the result into the caller's bytecode:

    * MACROS. `use Spark.Dsl` expands spark's macro bodies INTO ash's modules.
      Ash's beams literally contain code generated by spark.
    * STRUCT LITERALS. `%Spark.Dsl.Entity{}` in ash's source inlines spark's
      field list as a literal map in ash's beam.
    * COMPILE-TIME EVALUATION. `@x Foo.bar()` at module level freezes a value.

  So bumping `spark` changes ash's correct bytecode while ash's own version and
  checksum are byte-identical. A flat `<dep>:<version>` key serves the stale ash
  forever, and nothing detects it: dependency staleness is decided from
  `.mix/compile.lock` and `.mix/compile.elixir_scm` — the lock entry and the SCM,
  and nothing about the surrounding dependency set.

  Mix gets this right in a normal build: it tracks compile-time dependencies and
  recompiles dependents. **A cache restore steps around that machinery entirely**,
  so the key has to re-establish at the cache layer the invariant Mix maintains
  at the compile layer. That is the whole argument for the recursion.

  Hashing the OUTPUT instead — module names, beam counts, export sets — cannot
  work, for two separate reasons. It is unsound (measured: `oban` has an
  identical module set across six consumers while `Mix.Tasks.Oban.Install` gains
  five functions in one of them), and more fundamentally it is the wrong kind of
  thing: an output hash can only be computed AFTER compiling, which is the cost
  being avoided. Output hashes address objects. Input hashes are keys.

  The alternative sound key — hash the whole lockfile — invalidates every package
  on any lock change whatsoever. The recursion is what buys PRECISION: bumping
  `spark` invalidates spark and the packages above it, and leaves `postgrex`,
  `telemetry` and `bcrypt_elixir` alone.

      key(dep) = sha256(
        schema_version,                       # retires the whole store
        elixir, otp, erts, arch, mix_env,     # the toolchain
        ERL_COMPILER_OPTIONS, ELIXIR_ERL_OPTIONS, MIX_TARGET,
        [os_release, cc]                      # only for a dependency with a native build
        name, version, inner_checksum,        # the dep's own source (the lock entry)
        build_tools,                          # mix / rebar3 / make, from the lock
        env, compile, system_env,             # the declaration's build options (Mix's)
        config_digest(dep.app),               # compile-time config reaching it
        for each declared child, sorted:
          optional and absent -> ("absent", name)
          otherwise           -> ("present", name, key(child))   # <- recursion
      )

  Every input is either the lock entry or a field of the `%Mix.Dep{}` Mix
  itself converged (`Depdep.Deps`); nothing is re-derived. A dependency
  compiled under another `env:` than `:prod`, with a custom `compile:` command
  or with `system_env:` set produces different bytecode from the same source,
  and those three were not in the key before v3 (#89).

  Because each node contributes its own app's config and folds in its children,
  a dependency's closure accumulates config for exactly the apps in that closure
  and no others.

  ## What an object carries that is not a key input

  Two things travel inside an object and are deliberately not hashed. Mix's
  Erlang compiler manifest (`.mix/compile.erlang`) records the **pusher's
  absolute beam paths**; it is read only when Mix decides to recompile the
  dependency, and then it makes Mix recompile the `.erl` files it lists —
  a few files, once, never a wrong build. Mix's Elixir manifest records
  relative source paths and the directory it was compiled in, which it
  checks only when compiling. Neither changes what a restored dependency
  *is*, so neither is in the key; `Depdep.RestoreCheck` is what notices when
  Mix would rebuild a restored unit for any reason.

  A dependency resolves to `{:key, hash}` or `{:skip, reason}`. `:skip`
  propagates upward: a dependency whose child cannot be keyed cannot itself be
  keyed, because its own output depends on that child's. That is the fail-safe
  direction — it costs a compile, never a wrong restore.
  """

  # v2 is when objects gained `deps/` alongside `_build/`. v3 is when the key's
  # inputs became Mix's own (#89): the build options a declaration carries —
  # `env:`, `compile:`, `system_env:` — joined the key, so no v2 object can be
  # trusted to have been built the way a v3 key says. The prefix is in the key
  # precisely so a change to what an object CONTAINS or what its key MEANS
  # retires every old object rather than mixing shapes.
  #
  # CHANGING THIS INVALIDATES EVERY CONSUMER'S STORE AT ONCE. It is a breaking
  # change in the semver sense and needs a major version and a migration note,
  # not an edit.
  @schema "v3"

  # Schemas depdep no longer reads or writes. An object under one of these prefixes
  # **cannot be requested by any running depdep**, because `object/3` builds every path
  # from `@schema` — so it is unreachable by construction, whatever the roots say, and
  # `Depdep.Sweep` removes it without marking (#166, for #140).
  #
  # Adding a schema that is still in use would delete live objects. That is the one way
  # this list can cause real loss, so a test asserts `@schema` is never in it. The list
  # is a deliberate, reviewed act — the same weight as changing `@schema` itself.
  @retired ["v2"]

  @doc "The schema version this build of depdep reads and writes."
  def schema, do: @schema

  @doc """
  Schema versions depdep has retired.

  An object under one of these prefixes is unreachable by construction: every path
  `object/3` builds begins with `schema/0`, so nothing depdep runs will ever ask for it.
  Reclamation removes them without consulting the live set
  (`spec/08-reclamation.md#prefixes`), which is what makes retiring a schema a matter of
  writing under a new prefix **and removing the old one**
  (`spec/03-keys.md#object-path`).
  """
  def retired, do: @retired

  def digest(parts),
    do: :crypto.hash(:sha256, Enum.join(parts, "\n")) |> Base.encode16(case: :lower)

  @doc """
  The toolchain half of every key: `%{base: parts, native: parts}`.

  `base` is in every key: the Elixir and OTP the bytecode was produced by,
  the ERTS and the architecture a beam or a NIF is loaded into, the
  `MIX_ENV`, and the three environment variables that change what the
  compilers emit (`ERL_COMPILER_OPTIONS`, `ELIXIR_ERL_OPTIONS`, `MIX_TARGET`
  — empty when unset, so unset is one value). Before v3 only the first two
  and the env were here, and every NIF object in the store was x86-64 bytes
  with nothing in its key to say so (#89).

  `native` is folded in only for a dependency with a native build
  (`native?/1`): the OS release and the C compiler, which are what its bytes
  additionally depend on. A dependency without one does not rekey when the
  image's `gcc` moves. Separated so tests can hold both fixed.
  """
  def toolchain(env) do
    %{
      base: [
        "elixir=#{System.version()}",
        "otp=#{:erlang.system_info(:otp_release)}",
        "erts=#{:erlang.system_info(:version)}",
        "arch=#{:erlang.system_info(:system_architecture)}",
        "env=#{env}",
        "erl_compiler_options=#{System.get_env("ERL_COMPILER_OPTIONS") || ""}",
        "elixir_erl_options=#{System.get_env("ELIXIR_ERL_OPTIONS") || ""}",
        "mix_target=#{System.get_env("MIX_TARGET") || ""}"
      ],
      native: [
        "os=#{Depdep.Provider.Apt.suite()}",
        "cc=#{cc_version()}"
      ]
    }
  end

  # The first line of `cc --version`, or `none`: a machine with no C compiler
  # cannot have built a NIF, and one that gains a compiler later must not
  # match objects built without one.
  defp cc_version do
    case System.find_executable("cc") do
      nil ->
        "none"

      cc ->
        case System.cmd(cc, ["--version"], stderr_to_stdout: true) do
          {out, 0} -> out |> String.split("\n", parts: 2) |> hd() |> String.trim()
          {_, _} -> "unknown"
        end
    end
  end

  @native_tools ~w(elixir_make rustler rustler_precompiled zigler zigler_precompiled cc_precompiler)

  @doc """
  Whether a dependency's build produces native code, from its lock entry
  alone — fetched or not.

  A NIF or port program is built by a tool the dependency declares:
  `elixir_make`, `rustler` (or `rustler_precompiled`, which downloads a
  build for this target — native bytes all the same), `zigler`,
  `cc_precompiler`; or the dependency is `make`-managed. Those names are in
  the lock entry's child list, which is why this needs no source on disk.
  """
  def native?(%{entry: entry, children: children}) do
    tools = if children == :unknown, do: [], else: Enum.map(children, &elem(&1, 0))

    Enum.any?(tools, &(&1 in @native_tools)) or
      (Depdep.Lock.hex?(entry) and :make in elem(entry, 4))
  end

  @doc """
  `%{name => {:key, hash} | {:skip, reason}}` for every entry in the lock.

  Returns `{:error, {:cycle, name}}` rather than looping. Hex's resolver cannot
  produce a cycle, so this is a guard against a malformed lock rather than an
  expected state — but the alternative is a hang with no explanation.
  """
  def compute(deps, config, toolchain) do
    deps
    |> Map.keys()
    |> Enum.sort()
    |> Enum.reduce_while({:ok, %{}}, fn name, {:ok, acc} ->
      case resolve(name, deps, config, toolchain, acc, MapSet.new()) do
        {:ok, acc} -> {:cont, {:ok, acc}}
        {:error, e} -> {:halt, {:error, e}}
      end
    end)
  end

  defp resolve(name, deps, config, toolchain, acc, visiting) do
    cond do
      Map.has_key?(acc, name) ->
        {:ok, acc}

      MapSet.member?(visiting, name) ->
        {:error, {:cycle, name}}

      true ->
        resolve_dep(
          name,
          Map.fetch!(deps, name),
          deps,
          config,
          toolchain,
          acc,
          MapSet.put(visiting, name)
        )
    end
  end

  defp resolve_dep(name, %{children: :unknown}, _deps, _config, _toolchain, acc, _visiting) do
    {:ok,
     Map.put(
       acc,
       name,
       {:skip, "git dependency — its dependencies are unknown until mix deps.get"}
     )}
  end

  defp resolve_dep(name, dep, deps, config, toolchain, acc, visiting) do
    present = Enum.filter(dep.children, fn {child, _opt} -> Map.has_key?(deps, child) end)

    case Enum.reduce_while(present, {:ok, acc}, fn {child, _}, {:ok, acc} ->
           case resolve(child, deps, config, toolchain, acc, visiting) do
             {:ok, acc} -> {:cont, {:ok, acc}}
             {:error, e} -> {:halt, {:error, e}}
           end
         end) do
      {:error, e} -> {:error, e}
      {:ok, acc} -> {:ok, Map.put(acc, name, key_for(name, dep, deps, config, toolchain, acc))}
    end
  end

  defp key_for(name, dep, deps, config, toolchain, acc) do
    entry = dep.entry

    skipped =
      Enum.find(dep.children, fn {child, _} ->
        Map.has_key?(deps, child) and match?({:skip, _}, Map.fetch!(acc, child))
      end)

    case skipped do
      {child, _} ->
        {:skip, "depends on #{child}, which cannot be keyed"}

      nil ->
        # A child ABSENT from the lock is an unresolved optional dependency, and
        # its absence is exactly what changes the parent's compiled output —
        # `ash` guards whole source files on `Code.ensure_loaded?(Plug)`. So
        # absence is recorded positively rather than omitted.
        child_parts =
          Enum.map(dep.children, fn {child, _optional} ->
            case Map.get(acc, child) do
              {:key, hash} -> "present #{child} #{hash}"
              nil -> "absent #{child}"
            end
          end)

        parts =
          [@schema] ++
            toolchain.base ++
            if(native?(dep), do: toolchain.native, else: []) ++
            [
              "name=#{name}",
              "version=#{Depdep.Lock.version(entry)}",
              "source=#{Depdep.Lock.inner_checksum(entry)}",
              "tools=#{Depdep.Lock.build_tools(entry)}",
              "env=#{dep.env}",
              "compile=#{dep.compile || ""}",
              "system_env=#{inspect(dep.system_env)}",
              "config=#{Depdep.Config.digest_for(config, name)}"
            ] ++ child_parts

        {:key, digest(parts)}
    end
  end

  @doc "Where an object lives. Readable rather than flat, so the store can be browsed."
  def object(name, entry, hash),
    do: "#{@schema}/#{name}/#{Depdep.Lock.version(entry)}/#{hash}.tar.gz"
end
