defmodule Depdep.Key do
  @moduledoc """
  The recursive Merkle key.

  A dependency's compiled output is a function of its dependencies' compiled
  output, not just its own source. Elixir resolves a great deal at compile time
  and bakes the result into the caller's bytecode:

    * MACROS. `use Spark.Dsl` expands spark's macro bodies INTO ash's modules.
      Ash's beams literally contain code generated by spark.
    * STRUCT LITERALS. `%Spark.Dsl.Entity{}` in ash's source inlines spark's
      field list as a literal map in ash's beam.
    * COMPILE-TIME EVALUATION. `@x Foo.bar()` at module level freezes a value.

  So bumping `spark` changes ash's correct bytecode while ash's own version and
  checksum are byte-identical. A flat `<dep>:<version>` key serves the stale ash
  forever, and nothing detects it: dependency staleness is decided from
  `.mix/compile.lock` and `.mix/compile.elixir_scm` — the lock entry and the SCM,
  and nothing about the surrounding dependency set.

  Mix gets this right in a normal build: it tracks compile-time dependencies and
  recompiles dependents. **A cache restore steps around that machinery entirely**,
  so the key has to re-establish at the cache layer the invariant Mix maintains
  at the compile layer. That is the whole argument for the recursion.

  Hashing the OUTPUT instead — module names, beam counts, export sets — cannot
  work, for two separate reasons. It is unsound (measured: `oban` has an
  identical module set across six consumers while `Mix.Tasks.Oban.Install` gains
  five functions in one of them), and more fundamentally it is the wrong kind of
  thing: an output hash can only be computed AFTER compiling, which is the cost
  being avoided. Output hashes address objects. Input hashes are keys.

  The alternative sound key — hash the whole lockfile — invalidates every package
  on any lock change whatsoever. The recursion is what buys PRECISION: bumping
  `spark` invalidates spark and the packages above it, and leaves `postgrex`,
  `telemetry` and `bcrypt_elixir` alone.

      key(dep) = sha256(
        schema_version,                       # retires the whole store
        name, version, inner_checksum,        # the dep's own source
        elixir, otp, mix_env, build_tools,    # the toolchain
        config_digest(dep.app),               # compile-time config reaching it
        for each declared child, sorted:
          optional and absent -> ("absent", name)
          otherwise           -> ("present", name, key(child))   # <- recursion
      )

  Because each node contributes its own app's config and folds in its children,
  a dependency's closure accumulates config for exactly the apps in that closure
  and no others.

  A dependency resolves to `{:key, hash}` or `{:skip, reason}`. `:skip`
  propagates upward: a dependency whose child cannot be keyed cannot itself be
  keyed, because its own output depends on that child's. That is the fail-safe
  direction — it costs a compile, never a wrong restore.
  """

  # v2 is when objects gained `deps/` alongside `_build/`. A v1 object holds only
  # half of what a v2 restore expects, and the difference is invisible at restore
  # time — it just recompiles. The prefix is in the key precisely so a change to
  # what an object CONTAINS retires every old object rather than mixing shapes.
  #
  # CHANGING THIS INVALIDATES EVERY CONSUMER'S STORE AT ONCE. It is a breaking
  # change in the semver sense and needs a major version and a migration note,
  # not an edit.
  @schema "v2"

  @doc "The schema version this build of depdep reads and writes."
  def schema, do: @schema

  def digest(parts),
    do: :crypto.hash(:sha256, Enum.join(parts, "\n")) |> Base.encode16(case: :lower)

  @doc "The toolchain half of every key. Separated so tests can hold it fixed."
  def toolchain(env) do
    [
      "elixir=#{System.version()}",
      "otp=#{:erlang.system_info(:otp_release)}",
      "env=#{env}"
    ]
  end

  @doc """
  `%{name => {:key, hash} | {:skip, reason}}` for every entry in the lock.

  Returns `{:error, {:cycle, name}}` rather than looping. Hex's resolver cannot
  produce a cycle, so this is a guard against a malformed lock rather than an
  expected state — but the alternative is a hang with no explanation.
  """
  def compute(lock, config, toolchain) do
    lock
    |> Map.keys()
    |> Enum.sort()
    |> Enum.reduce_while({:ok, %{}}, fn name, {:ok, acc} ->
      case resolve(name, lock, config, toolchain, acc, MapSet.new()) do
        {:ok, acc} -> {:cont, {:ok, acc}}
        {:error, e} -> {:halt, {:error, e}}
      end
    end)
  end

  defp resolve(name, lock, config, toolchain, acc, visiting) do
    cond do
      Map.has_key?(acc, name) ->
        {:ok, acc}

      MapSet.member?(visiting, name) ->
        {:error, {:cycle, name}}

      true ->
        entry = Map.fetch!(lock, name)
        resolve_entry(name, entry, lock, config, toolchain, acc, MapSet.put(visiting, name))
    end
  end

  defp resolve_entry(name, entry, lock, config, toolchain, acc, visiting) do
    case Depdep.Lock.children(entry) do
      :unknown ->
        {:ok, Map.put(acc, name, {:skip, "git dependency — the lock carries no dependency list"})}

      children ->
        present = Enum.filter(children, fn {child, _opt} -> Map.has_key?(lock, child) end)

        case Enum.reduce_while(present, {:ok, acc}, fn {child, _}, {:ok, acc} ->
               case resolve(child, lock, config, toolchain, acc, visiting) do
                 {:ok, acc} -> {:cont, {:ok, acc}}
                 {:error, e} -> {:halt, {:error, e}}
               end
             end) do
          {:error, e} ->
            {:error, e}

          {:ok, acc} ->
            {:ok,
             Map.put(acc, name, key_for(name, entry, children, lock, config, toolchain, acc))}
        end
    end
  end

  defp key_for(name, entry, children, lock, config, toolchain, acc) do
    skipped =
      Enum.find(children, fn {child, _} ->
        Map.has_key?(lock, child) and match?({:skip, _}, Map.fetch!(acc, child))
      end)

    case skipped do
      {child, _} ->
        {:skip, "depends on #{child}, which cannot be keyed"}

      nil ->
        # A child ABSENT from the lock is an unresolved optional dependency, and
        # its absence is exactly what changes the parent's compiled output —
        # `ash` guards whole source files on `Code.ensure_loaded?(Plug)`. So
        # absence is recorded positively rather than omitted.
        child_parts =
          Enum.map(children, fn {child, _optional} ->
            case Map.get(acc, child) do
              {:key, hash} -> "present #{child} #{hash}"
              nil -> "absent #{child}"
            end
          end)

        parts =
          [@schema] ++
            toolchain ++
            [
              "name=#{name}",
              "version=#{Depdep.Lock.version(entry)}",
              "source=#{Depdep.Lock.inner_checksum(entry)}",
              "tools=#{Depdep.Lock.build_tools(entry)}",
              "config=#{Depdep.Config.digest_for(config, name)}"
            ] ++ child_parts

        {:key, digest(parts)}
    end
  end

  @doc "Where an object lives. Readable rather than flat, so the store can be browsed."
  def object(name, entry, hash),
    do: "#{@schema}/#{name}/#{Depdep.Lock.version(entry)}/#{hash}.tar.gz"
end
